[package]
name = "wordle"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.8", features = ["derive"] }
chrono = "0.4.19"
crossterm = "0.23.2"
tui = { version = "0.17.0", default-features = false, features = ['crossterm'] }
rand = "0.8.5"